name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust if necessary

    - name: Run Tests
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test_data/output_test1.txt
        python3 find_lowest_number.py test_data/test2_input.txt test_data/output_test2.txt
        python3 find_lowest_number.py test_data/test3_input.txt test_data/output_test3.txt

    - name: Compare Outputs
      run: |
        diff -u test_data/output_test1.txt test_data/test1_expected.txt
        diff -u test_data/output_test2.txt test_data/test2_expected.txt
        diff -u test_data/output_test3.txt test_data/test3_expected.txt
